[buildPlans.IosevkaClear]
family = "Iosevka Clear"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaClear.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "crossing-baseline"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-serifless"
g = "single-storey-serifless"
i = "hooky"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClear.variants.italic]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "open-swash"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClear.variants.oblique]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "open-swash"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClear.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaClear.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaClear.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaClear.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaClear.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaClear.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaClear.metricOverride]
leading = 1500

[buildPlans.IosevkaClearType]
family = "Iosevka Clear Type"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaClearType.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "open-swash"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
i = "hooky"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClearType.variants.italic]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "open-swash"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClearType.variants.oblique]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
capital-p = "closed-serifless"
capital-q = "open-swash"
a = "single-storey-earless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
y = "cursive-serifless"
lower-delta = "flat-top"
lower-theta = "capsule"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "semi-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "flat-top-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "compact"
dollar = "through-cap"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "force-upright"
question = "corner-flat-hooked"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClearType.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaClearType.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaClearType.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaClearType.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaClearType.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaClearType.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaClearType.metricOverride]
leading = 1500
