[buildPlans.IosevkaClear]
family = "Iosevka Clear"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaClear.variants.design]
one = "base"
two = "straight-neck-serifless"
four = "closed-serifless"
five = "upright-flat-serifless"
six = "open-contour"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "straight-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothed-inward-serifed-hookless"
capital-j = "serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-m = "flat-bottom-serifless"
capital-p = "open-serifless"
capital-q = "crossing-baseline"
capital-r = "curly-open-serifless"
capital-u = "toothless-corner-serifless"
capital-w = "straight-flat-top-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "tailed-crossbar-at-x-height"
g = "single-storey-earless-rounded"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
m = "short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "hookless-top-serifed"
t = "flat-hook-short-neck2"
u = "toothless-corner-serifless"
w = "straight-serifless"
y = "cursive-serifless"
capital-gamma = "serifed"
lower-delta = "flat-top"
lower-iota = "tailless-serifed"
capital-lambda = "straight-tri-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-motion-serifed"
lower-pi = "tailless"
lower-tau = "flat-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifed"
lower-psi = "flat-top-serifless"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "open-cap"
cent = "open-cap"
percent = "rings-continuous-slash-also-connected"
question = "corner-flat-hooked"
micro-sign = "tailed-motion-serifed"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClear.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaClear.metricOverride]
leading = 1500
