[buildPlans.IosevkaClear]
family = "Iosevka Clear"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaClear.variants.design]
one = "base"
two = "straight-neck-serifless"
four = "closed-serifless"
five = "upright-flat-serifless"
six = "open-contour"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "straight-serifless"
capital-b = "standard-interrupted-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothed-inward-serifed-hookless"
capital-j = "serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-m = "flat-bottom-serifless"
capital-p = "open-serifless"
capital-q = "crossing-baseline"
capital-r = "curly-open-serifless"
capital-u = "toothless-corner-serifless"
capital-w = "straight-flat-top-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothed-serifless"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
m = "serifless"
n = "straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "hookless-serifless"
t = "flat-hook-short-neck2"
u = "toothless-corner-serifless"
w = "straight-serifless"
y = "cursive-serifless"
capital-gamma = "serifed"
lower-delta = "flat-top"
lower-iota = "tailless-serifed"
capital-lambda = "straight-tri-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-motion-serifed"
lower-pi = "tailless"
lower-tau = "flat-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifed"
lower-psi = "flat-top-serifless"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "open-cap"
cent = "open-cap"
percent = "rings-continuous-slash-also-connected"
question = "corner-flat-hooked"
micro-sign = "tailed-motion-serifed"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClear.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaClear.metricOverride]
leading = 1500

[buildPlans.IosevkaClearType]
family = "Iosevka Clear Type"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaClearType.variants.design]
one = "base"
two = "straight-neck-serifed"
four = "closed-non-crossing-serifed"
five = "upright-flat-serifed"
six = "open-contour"
seven = "straight-serifed-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "straight-top-serifed"
capital-b = "standard-interrupted-unilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-inward-serifed-hookless"
capital-h = "top-left-serifed"
capital-j = "serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-l = "serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "open-swash"
capital-r = "curly-open-top-left-and-bottom-right-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "curly-top-serifed"
a = "single-storey-earless-corner-serifed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothed-top-serifed"
e = "rounded"
f = "flat-hook-serifed"
g = "single-storey-serifless"
h = "straight-top-left-serifed"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-connected-top-left-serifed"
m = "short-leg-top-left-serifed"
n = "straight-top-left-serifed"
p = "earless-corner-serifed"
q = "earless-corner-straight-serifed"
r = "corner-hooked-top-serifed"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck2"
u = "toothless-rounded-motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-unilateral-motion-serifed"
y = "cursive-motion-serifed"
z = "curly-top-serifed"
capital-gamma = "serifed"
lower-delta = "flat-top"
lower-iota = "tailless-serifed"
capital-lambda = "straight-tri-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-motion-serifed"
lower-pi = "tailless"
lower-tau = "flat-tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-straight-serifed"
lower-psi = "flat-top-serifless"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "open-cap"
cent = "open-cap"
percent = "rings-continuous-slash-also-connected"
question = "corner-flat-hooked"
micro-sign = "tailed-motion-serifed"
decorative-angle-brackets = "short"

[buildPlans.IosevkaClearType.widths.Normal]
shape = 600
menu = 5
css = "normal"
