name: Build Fonts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.0.0'
      - uses: ConorMacBride/install-package@v1
        with:
          apt: ttfautohint libttfautohint-dev
      - uses: actions/checkout@v4
        with:
          repository: 'be5invis/Iosevka'
          path: 'src'
      - name: Build Custom font
        run: |
          cp private-build-plans.toml src/private-build-plans.toml
          cd src
          npm install
          sed -i '/release = true/d' build-plans.toml
          npm run build -- release:archives
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.0.1
          files: |
            src/release-archives/PkgTTC-IosevkaClear-33.0.0.zip
            src/release-archives/PkgTTF-IosevkaClear-33.0.0.zip
            src/release-archives/PkgTTF-Unhinted-IosevkaClear-33.0.0.zip
            src/release-archives/PkgWebFont-IosevkaClear-33.0.0.zip
            src/release-archives/PkgWebFont-Unhinted-IosevkaClear-33.0.0.zip
            src/release-archives/SuperTTC-IosevkaClear-33.0.0.zip
          body: release
