name: Build Fonts

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.fontname }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fontName: ["IosevkaClear", "IosevkaClearType"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.0.0'

      - uses: ConorMacBride/install-package@v1
        with:
          apt: ttfautohint libttfautohint-dev

      - uses: actions/checkout@v4
        with:
          repository: 'be5invis/Iosevka'
          path: 'src'

      - name: Build ${{ matrix.fontName }}
        run: |
          cp private-build-plans.toml src/private-build-plans.toml
          cd src
          npm install
          npm run build -- ttf::${{ matrix.fontName }}

      - name: Zip ${{ matrix.fontName }}.zip
        run: |
          mkdir -p artifacts
          zip -r artifacts/${{ matrix.fontName }}.zip src/dist/${{ matrix.fontName }}

      - name: Upload ${{ matrix.fontName }}.zip to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 0.0.5
          files: artifacts/${{ matrix.fontName }}.zip
