name: Build Fonts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.0.0'
      - name: Get system packages
        run: sudo apt-get update && sudo apt-get install ttfautohint libttfautohint-dev
      - uses: actions/checkout@v4
        with:
          repository: 'be5invis/Iosevka'
          path: 'src'
      - name: Build Custom font
        run: |
          cp private-build-plans.toml src/private-build-plans.toml
          cd src
          npm install
          sed -i '/release = true/d' build-plans.toml
          npm run build -- release:archives
      - name: List all files in a directory
        run: ls -la src/release-archives
